export const MANAGEMENT_MODULES = {
  TRAVEL: "TRAVEL_MANAGEMENT",
  LECTURE: "LECTURE_TRANSACTION",
  SUPPLIES_REGISTER: "SUPPLIES_REGISTER",
  MAINTENANCE: "MAINTENANCE_MANAGEMENT",
  EXAM_SCHEDULE: "EXAM_SCHEDULE",
  HONORARIUM: "HONORARIUM_REGISTER",
  LOAN_LEDGER: "LOAN_LEDGER_MANAGEMENT",
  FUEL_ALLOWANCE: "FUEL_ALLOWANCE_MANAGEMENT",
  OVERTIME_LEDGER: "OVERTIME_LEDGER_MANAGEMENT",
  TRAVELLING_CLAIM: "TRAVELLING_CLAIM_MANAGEMENT",
  HOLIDAY_PAYMENT: "HOLIDAY_PAYMENT_MANAGEMENT",
  ADVANCE_SETTLEMENT: "ADVANCE_SETTLEMENT_MANAGEMENT",
   MISCELLANEOUS: "MISCELLANEOUS_MANAGEMENT",
   RESEARCH_GRANT: "RESEARCH_GRANT_MANAGEMENT",
   PETTY_CASH: "PETTY_CASH_MANAGEMENT",
   CONSTRUCTION_PAYMENTS: "CONSTRUCTION_PAYMENTS_MANAGEMENT",
   UTILITY_EXPENSE: "ELECTRICITY_WATER_COMMUNICATION_MANAGEMENT",
   VISITING_PAYMENT: "VISITING_PAYMENT_MANAGEMENT",
   AGAHARA_INSURANCE: "AGAHARA_INSURANCE_MANAGEMENT",
    UNIVERSITY_DEVELOPMENT_FUND: "UNIVERSITY_DEVELOPMENT_FUND_MANAGEMENT",
    COURSE_FEE: "COURSE_FEE_MANAGEMENT",
    REPAIR_SERVICE_PAYMENTS: "REPAIR_SERVICE_PAYMENTS_MANAGEMENT",
    CGU_PROGRAMS: "CGU_PROGRAMS_MANAGEMENT",
    SDC_PROGRAMS: "SDC_PROGRAMS_MANAGEMENT",
    RESEARCH_CONFERENCES: "RESEARCH_CONFERENCES_MANAGEMENT",
    FOREIGN_STUDENTS_PAYMENT: "FOREIGN_STUDENTS_PAYMENT_MANAGEMENT",
    LEDGER_SHEET_MANAGEMENT: "LEDGER_SHEET_MANAGEMENT"










};

export const ALL_MODULES = Object.values(MANAGEMENT_MODULES);
